### ISSUE TITLE
Top google result for "filforward" returns 404 link to misspelled URL

### ISSUE THREAD

**Issue by meandavejustice** [filecoin-project/filecoin-docs#2192]
Top result when searching "filforward" is a 404, notice the misspelled in the top indexed result URL.

![image](https://github.com/filecoin-project/filecoin-docs/assets/1844554/320ec190-ea59-4832-bb80-ece8802240f3)

Hopefully this indexing issue will correct itself, but may be worthwhile to put a redirect at: `https://docs.filecoin.io/smart-contracts/filecoin-evm-runtime/filforwader/`

May be related to #2184

**Comment by johnnymatthews** [comment]
Thanks for raising this! Should be fixed in #2195.

**Comment by meandavejustice** [comment]
hey @johnnymatthews Unfortunately this does not solve the issue.

The url that will need a redirect is: `/smart-contracts/filecoin-evm-runtime/filforwader/`

*note the misspelling of `filforwader`

The change is the referenced commit is:

[`smart-contracts/filforwarder: basics/assets/transfer-fil.md` in .gitbook.yaml](https://github.com/filecoin-project/filecoin-docs/commit/3a3fdf9e90cbed52ba440ed630ca45a019cad2d7#diff-3bdea6261687f749bccd68763ce01cfe6249305137f746ef6ef7c3f7eadebd0dR178)

I suggest an addition line of:
``` yaml
# fixes https://github.com/filecoin-project/filecoin-docs/issues/2192
`/smart-contracts/filecoin-evm-runtime/filforwader/: basics/assets/transfer-fil.md`
```

**Comment by johnnymatthews** [comment]
Oh wow, my bad. What a frustrating typo! I'll update now.
